### ISSUE TITLE
yoyow_client issues

### ISSUE THREAD

**Issue by kimziv** [yoyow-org/yoyow-core-testnet#1]
run ./yoyow_client  occur errors below:

    Timer Expired
      {"message":"Timer Expired"}
      asio  websocket.cpp:449 operator()

    {"uri":"ws://localhost:8090"}
    th_a  websocket.cpp:678 connect

how to solve it?

**Comment by yoyow-dev** [comment]
启动节点时带 --rpc-endpoint 参数
