### ISSUE TITLE
节点交易缓存问题

### ISSUE THREAD

**Issue by abitmore** [yoyow-org/yoyow-core-testnet#6]
群里看到的情况。
如果一个节点卡住，没有新块进来，用 client 连到这个节点广播交易时，显示广播成功，然后数据库状态已经发生变化。而实际上该交易还没有进块。比如，广播一个创建见证人的交易，然后用 get_witness 命令就能查到，以为是已经创建成功，而实际上这个交易当时还没被打包进块。过一会，当一个新块进来后，如果没有包含这个交易，再用 get_witness 查就发现没有了。

**Comment by yoyowd** [comment]
这是个功能，不是BUG。
